### ISSUE TITLE
當手持武器且處於半自動狀態時暫停遊戲，點擊返回遊戲會開一槍

### ISSUE THREAD

**Issue by tobiichi3227** [MCModderAnchor/TimelessAndClassicsZero#16]
我有做一些測試
在上述的情況下，`InputEvent.MouseInputEvent`中`Minecraft.getInstance().screen`會是`null`，可能沒辦法透過這個判斷

**Comment by TartaricAcid** [comment]
已知问题，有点不太好办

**Comment by tobiichi3227** [comment]
Ok（我也覺得不太好實現

**Comment by 286799714** [comment]
感觉这个小问题就没必要修了，如果你觉得ok就关闭issue吧

**Comment by tobiichi3227** [comment]
好
瑕不掩瑜
