### ISSUE TITLE
在inspect時射擊動畫會重疊在一起，而不是單純的射擊動畫

### ISSUE THREAD

**Issue by tobiichi3227** [MCModderAnchor/TimelessAndClassicsZero#9]

**Comment by 286799714** [comment]
马上修，以后射击会直接打断检视

**Comment by tobiichi3227** [comment]
謝謝啦
每天更新很頻繁，辛苦了

**Comment by 286799714** [comment]
[commit #326](https://github.com/MCModderAnchor/TimelessAndClassicsZero/commit/7477b7c137a42c131d40c29fb7d0d3953cbe6f4c)
